{% set version = "1.22.1-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-asioheaders
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/AsioHeaders_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/AsioHeaders/AsioHeaders_{{ version }}.tar.gz
  sha256: 1629c0ea78b8c63231ca62fcc39fce5d29919864050a8c331720ee9bbdea58a4

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('AsioHeaders')"           # [not win]
    - "\"%R%\" -e \"library('AsioHeaders')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=AsioHeaders
  license: BSL-1.0
  summary: "'Asio' is a cross-platform C++ library for network and low-level I/O programming that provides developers with a consistent asynchronous model using a modern C++ approach. It is also included in Boost but requires linking when used with Boost. Standalone it can be used header-only (provided a recent compiler).\
    \ 'Asio' is written and maintained by Christopher M. Kohlhoff, and released under the 'Boost Software License', Version 1.0."
  license_family: OTHER
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc

# Package: AsioHeaders
# Type: Package
# Title: 'Asio' C++ Header Files
# Version: 1.12.1-1
# Date: 2018-09-10
# Author: Dirk Eddelbuettel
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Description: 'Asio' is a cross-platform C++ library for network and low-level I/O programming that provides developers with a consistent asynchronous model using a modern C++ approach. It is also included in Boost but requires linking when used with Boost. Standalone it can be used header-only (provided a recent compiler). 'Asio' is written and maintained by Christopher M. Kohlhoff, and released under the 'Boost Software License', Version 1.0.
# Copyright: file inst/COPYRIGHTS
# License: BSL-1.0
# BugReports: https://github.com/eddelbuettel/asioheaders/issues
# NeedsCompilation: no
# Packaged: 2018-09-10 11:43:50.57711 UTC; edd
# Repository: CRAN
# Date/Publication: 2018-09-10 15:10:19 UTC
